# Generated by Django 3.2 on 2021-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('themaId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
